version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/rust"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Asia/Shanghai"
    target-branch: "master"
    open-pull-requests-limit: 100
    reviewers:
      - "XenoAmess"
    assignees:
      - "XenoAmess"
    commit-message:
      prefix: "build(deps)"
    labels:
      - "dependencies"
      - "rust"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Asia/Shanghai"
    target-branch: "master"
    open-pull-requests-limit: 100
    reviewers:
      - "XenoAmess"
    assignees:
      - "XenoAmess"
    commit-message:
      prefix: "ci"
    labels:
      - "dependencies"
      - "github-actions"
